# Plugin by Jon1Games
# Discord: jon1games
# GitHub: https://github.com/Jon1Games/

# Implemented plugins (usable in this Plugin):
# Minimessage (https://docs.advntr.dev/minimessage/format.html)

# Required Plugins
# LuckPerms
# PlaceHolderApi
  # /papi ecloud download luckperms

# Infos
# suggestionName is the name that shows up over the chat for you what you know what to type there.

EnableCalculatorCommand:
  Enabled: True
  suggestionName:
    Number: "Zahl"
  Aliases:
    - calc

CustomJoinQuitMessage:
  Enabled: true
  Messages:
  # Player placeholder: <player>
    JoinMessage: "<gray>[</gray><green>+</green><gray>]</gray> <player>"
    LeaveMessage: "<gray>[</gray><red>-</red><gray>]</gray> <player>"

MsgCommand:
  Enabled: true
  suggestionName:
    Message: "Nachricht"
    Player: "Spieler"
  # Remove Minecraft default Commands
  unregister:
    - "msg"
    - "tell"
    - "w"
  Aliases:
    - "message"
    - "msg"
    - "tell"
    - "wisper"
  # Placeholder: <toplayer> <frompalyer> <message>
  Messages:
    # Message for case the sender is the target
    same: "<red>Du kannst dir selbst keine Nachricht schicken!</red>"
    # Message for the MSG target
    To: "<gray>[</gray>Prefix<gray>]</gray> <fromplayer> -> <toplayer> <gold>:</gold> <message>"
    # Message for the MSG sender
    From: "<gray>[</gray>Prefix<gray>]</gray> <fromplayer> -> <toplayer> <gold>:</gold> <message>"

FlyCommand:
  Enabled: true
  Permission: "stuff.fly"
  suggestionName:
    Player: "Spieler"
  Aliases:
    - "fly"
  Messages:
    Self:
      EnterFlyMode: "Du bist in den Flugmodus gegangen."
      ExitFlyMode: "Du bist aus dem Flugmodus gegangen."
      ReturnInEnterFlyMode: "Der Flugmodus ist Aktiviert."
    # Player placeholder: <player>
    Other:
      Self:
        EnterFlyMode: "Du hast <green><player></green> in den Flugmodus gesetzt."
        ExitFlyMode: "Du hast <green><player></green> aus dem Flugmodus geholt."
      Other:
        EnterFlyMode: "Du wurdest von <green><player></green> in den Flugmodus gesetzt."
        OtherOtherExitFlyMode: "Du wurdest von <green><player></green> aus dem Flugmodus geholt."

FlySpeedCommand:
  Enabled: true
  Permission: "stuff.speed"
  suggestionName:
    Speed: "Geschwindigkeit"
    Player: "Spieelr"
  Aliases:
    - "flyspeed"
  # Speed placeholder: <speed>
  Messages:
    Self:
      NewSpeed: "Deine neue Fluggeschwindigkeit ist nun <gold><speed></gold>."
      ReturnSpeed: "Deine Fluggeschwindigkeit ist <gold><speed></gold>"
    # Player placeholder: <player>
    Other:
      SelfNewSpeed: "Deine neue Fluggeschwindigkeit wurde von <green><player></green> auf <gold><speed></gold> gesetzt."
      OtherNewSpeed: "Du hast die Fluggeschwindigkeit von <green><player></green> auf <gold><speed></gold>."

WalkSpeedCommand:
  Enabled: true
  Permission: "stuff.speed"
  suggestionName:
    Speed: "Geschwindigkeit"
    Player: "Spieler"
  Aliases:
    - "walkspeed"
  # Speed placeholder: <speed>
  Messages:
    Self:
      NewSpeed: "Deine neue Laufgeschwindigkeit ist nun <gold><speed></gold>."
      ReturnSpeed: "Deine Laufgeschwindigkeit ist <gold><speed></gold>"
    # Player placeholder: <player>
    Other:
      SelfNewSpeed: "Deine neue Laufgeschwindigkeit wurde von <green><player></green> auf <gold><speed></gold> gesetzt."
      OtherNewSpeed: "Du hast die Laufgeschwindigkeit von <green><player></green> auf <gold><speed></gold>."

GamemodeCommand:
  Enabled: true
  suggestionName:
    Player: "Spieler"
  Aliases:
    - "gm"
  # Player placeholder: <player> (only for the Other section)
  Messages:
    Creative:
      Aliases:
        - "1"
      Permission: "stuff.gamemode.creative"
      Self: "Dein Spielmodus wurde auf Kreativ gesetzt."
      Other:
        Self: "Du hast <green><player></green> in den Kreativ Modus gesetzt."
        Other: "Du wurdest von <green><player></green> in den Kreativ Modus gesetzt."
    Spectator:
      Aliases:
        - "3"
      Permission: "stuff.gamemode.spectator"
      Self : "Dein Spielmodus wurde auf Zuschauer gesetzt."
      Other:
        Self : "Du hast <green><player></green> in den Zuschauer Modus gesetzt."
        Other : "Du wurdest von <green><player></green> in den Zuschauer Modus gesetzt."
    Adventure:
      Aliases:
        - "2"
      Permission: "stuff.gamemode.adventure"
      Self : "Dein Spielmodus wurde auf Abenteuer gesetzt."
      Other:
        Self : "Du hast <green><player></green> in den Abenteuer Modus gesetzt."
        Other : "Du wurdest von <green><player></green> in den Abenteuer Modus gesetzt."
    Survival:
      Aliases:
        - "0"
      Permission: "stuff.gamemode.survival"
      Self : "Dein Spielmodus wurde auf Überleben gesetzt."
      Other:
        Self : "Du hast <green><player></green> in den Überleben Modus gesetzt."
        Other : "Du wurdest von <green><player></green> in den Überleben Modus gesetzt."

PortableInventoryCommand:
  Enabled: true
  WorkbenchPermission: "stuff.portableinventory.workbench"
  AnvilPermission: "stuff.portableinventory.anvil"
  GrindstonePermission: "stuff.portableinventory.grindstone"
  SmithingtablePermission: "stuff.portableinventory.smithingtable"

Format:
  PlayerNames:
    Enabled: true
    Prefix:
      Enabled: true
      Prefix: "%luckperms_prefix% "
    Suffix:
      Enabled: true
      Suffix: " %luckperms_suffix%"
    TabSorting:
        Enabled: true
        MaxWeight: 1000
  Chat:
    Enabled: true
    # Placeholder: <player>, <message>
    Format: "<player> <gray><message></gray>"
    # options vanilla (&4 text in dark red) and minimessage ( <red> text in red )
    ColorType: minimessage
    InChatPlaceholder:
      # displaying held item, placeholder: <i> <I> (only supported by ColorType: minimessage)
      ItemInHand: true

PlayTimeCommand:
  Enabled: true
  suggestionName:
    Player: "Spieler"
  Aliases:
    - "playtime"
  # Placeholders: for both: <days> <hours> <min> <sec> , for other: <player>
  Messages:
    self: "<green>Du hast <days> Tage, <hours> Stunden, <min> Minuten und <sec> Sekunden Spielzeit"
    other: "<green><player> hat <days> Tage, <hours> Stunden, <min> Minuten und <sec> Sekunden Spielzeit"

PingCommand:
  Enabled: true
  suggestionName:
    Player: "Spieler"
  Aliases:
    - "ping"
  # Placeholders: for both: <ping> , for other: <player>
  Messages:
    self: "Dein Ping beträgt <gold><ping><reset>."
    other: "Der Ping von <green><player><reset> Ping beträgt <gold><ping><reset>."

BroadcastCommand:
  Enabled: true
  Permission: "stuff.broadcast"
  suggestionName:
    Message: "Nachricht"
  Aliases:
    - "broadcast"
  # Placeholder: <message>
  Message: "<gray>[<red>Broadcast</red>]</gray> <message>"

InfoCommands:
  Enabled: true
  # Placeholders: <player>
  # You can add as many Commands here as you want
  Text:
    Enabled: true
    Aliases:
      - "text"
    Message: "Ein Text Text"

CommandCommand:
  Enabled: true
  # Placeholders: <player>
  # You can add as many Commands here as you want
  TestMessage:
    Enabled: true
    Aliases:
      - "testmessage"
    RunAsConsole: false
    Command: "say test"