# Plugin by Jon1Games
# Discord: jon1games
# GitHub: https://github.com/Jon1Games/

# Implemented plugins (usable in this Plugin):
# Minimessage (https://docs.advntr.dev/minimessage/format.html)

# Required Plugins
# Config API

# Suggested Plugins 
# LuckPerms
# PlaceHoderApi
# - /papi ecloud download luckperms

# Do not change the version.
config: "1"

EnableCalculatorCommand:
  Enabled: false
  Aliases:
    - calc

CustomJoinQuitMessage:
  Enabled: true
  Messages:
    # Player placeholder: <player>
    JoinMessage: "<gray>[</gray><green>+</green><gray>]</gray> <player>"
    LeaveMessage: "<gray>[</gray><red>-</red><gray>]</gray> <player>"

MsgCommand:
  Enabled: true
  Permission: "stuff.msg.send"
  # Remove Minecraft default Commands
  unregister:
    - "msg"
    - "tell"
    - "w"
  Aliases:
    - "message"
    - "msg"
    - "tell"
    - "wisper"
  # Quick answer last user who send you an msg
  AnswerCommand:
    Permission: "stuff.msg.answer"
    Aliases:
      - r

FlyCommand:
  Enabled: false
  Permission: "stuff.fly"
  Aliases:
    - "fly"
  Messages:
    Self:
      ReturnInEnterFlyMode: "Der Flugmodus ist Aktiviert."

FlySpeedCommand:
  Enabled: false
  Permission: "stuff.speed"
  Aliases:
    - "flyspeed"

WalkSpeedCommand:
  Enabled: false
  Permission: "stuff.speed"
  suggestionName:
    Speed: "Geschwindigkeit"
    Player: "Spieler"
  Aliases:
    - "walkspeed"

GamemodeCommand:
  Enabled: true
  Aliases:
    - "gm"
  Messages:
    Creative:
      Aliases:
        - "1"
      Permission: "stuff.gamemode.creative"
    Spectator:
      Aliases:
        - "3"
      Permission: "stuff.gamemode.spectator"
    Adventure:
      Aliases:
        - "2"
      Permission: "stuff.gamemode.adventure"
    Survival:
      Aliases:
        - "0"
      Permission: "stuff.gamemode.survival"

Format:
  PlayerNames:
    Enabled: false
    Prefix:
      Enabled: false
      Prefix: "%luckperms_prefix%"
    Suffix:
      Enabled: false
      Suffix: "%luckperms_suffix%"
    TabSorting:
      # Needs placeholderapi
      Enabled: false
      MaxWeight: 1000
  Chat:
    Enabled: true
    # Placeholder: <player>, <message>
    Format: "<player> <gray><message></gray>"
    # options vanilla (&4 text in dark red) and minimessage ( <red> text in red )
    ColorType: minimessage
    InChatPlaceholder:
      # displaying held item, placeholder: <i> <I> (only supported by ColorType: minimessage)
      ItemInHand: true

PlayTimeCommand:
  Enabled: true
  Aliases:
    - "playtime"

PingCommand:
  Enabled: false
  suggestionName:
    Player: "Spieler"
  Aliases:
    - "ping"

BroadcastCommand:
  Enabled: false
  Permission: "stuff.broadcast"
  Aliases:
    - "broadcast"
  # Placeholder: <message>
  Message: "<gray>[<red>Broadcast</red>]</gray> <message>"

TeleportCommands:
  Enabled: false
  Spawn:
    Enabled: false
    JoinTpToSpawn: false
    Permission: "stuff.teleport.spawn"
    # Default: overworld = world, nether = world_nether, end = world_the_end
    World: world
    Pos_X: 0
    Pos_Y: 0
    Pos_Z: 0
    Pos_YAW: 0
    Pos_PITCH: 0
    Aliases:
      - spawn
  SetSpawn:
    Enabled: false
    Permission: "stuff.teleport.setspawn"
    Aliases:
      - setspawn
  TPA:
    Enabled: false
    Permission: "stuff.teleport.tpa"
    Aliases:
      - tpa
    # in seconds
    RequestDuration: 60
    Cooldown: 30
    CooldownBypassPermission: "stuff.teleport.tpa.cooldown.bypass"
    NotMoveFor: 3
    NotMoveForBypassPermission: "stuff.teleport.tpa.notmovefor.bypass"
  TPAACCEPT:
    Enabled: false
    Permission: "stuff.teleport.tpac"
    Aliases:
      - tpac
      - tpaccept
      - tpaaccept
  TPADECLINE:
    Enabled: false
    Permission: "stuff.teleport.tpad"
    Aliases:
      - tpad
      - tpdecline
      - tpadecline
  RTP:
    Enabled: false
    Permission: "stuff.teleport.rtp"
    Aliases:
      - rtp
    Cooldown: 300
    CooldownBypassPermission: "stuff.teleport.rtp.cooldown.bypass"
    NotMoveFor: 3
    NotMoveForBypassPermission: "stuff.teleport.rtp.notmovefor.bypass"
    Worlds:
      # needs to be the worlds name
      # MinY and MaxY can be disabled by not setting it
      # For Disabled worlds do this (you can ignore the other settings if the world is disabled):
      # world:
      #   Enabled: False
      world:
        Enabled: True
        Permission: "stuff.teleport.rtp.worlds.world"
        MinDistance: 1000
        MaxDistance: 5000
        MinY: 50
        MaxY:
      world_nether:
        Enabled: True
        Permission: "stuff.teleport.rtp.worlds.world_nether"
        MinDistance: 500
        MaxDistance: 2500
        MinY: 25
        MaxY: 120
      world_the_end:
        Enabled: True
        Permission: "stuff.teleport.rtp.worlds.world_the_end"
        MinDistance: 2000
        MaxDistance: 7000
        MinY:
        MaxY:

SwitchChannel:
  Enabled: false
  Permission: "stuff.switchchannel"
  Aliases:
    - "kanal"
    - "channel"
  DefaultChannelName: "Standart"

FirstJoinTitle:
  Enabled: false
  # Placeholder: <player>
  Title: "Wilkommen"
  SubTitle: "<player>"

FirstJoniMessage:
  Enabled: false
  # Placeholder: <player>
  Message: "Willkommen auf unserem Server <player>."

Channels:
  Admin:
    Enabled: false
    Permission:
      See: "stuff.adminchannel.see"
      Join: "stuff.adminchannel.join"
    # Only affects if player can write but not see messages
    CanSeeOwnMessages: true
    # Placeholder: <player>, <message>
    Format: "<gray>[<red>Admin</red>]</gray> <player> <gray><message></gray>"

InfoCommands:
  Enabled: false
  # Placeholders: <player>
  # You can add as many Commands here as you want
  ExampleCommand:
    Enabled: false
    Aliases:
      - "ExmapleCommand"
    Message: "Ein Text Text"

CommandCommand:
  Enabled: false
  # Placeholders: <player>
  # You can add as many Commands here as you want
  TestMessage:
    Enabled: false
    Aliases:
      - "testmessage"
    Permission: "stuff.commandcommand.testmessage"
    RunAsConsole: false
    Command: "say test"

Sudo:
  Enabled: false
  Aliases:
    - "sudo"
  Permission: "stuff.sudo"
  # Player with bypass permission wont be able to be sudoed
  BypassPermission: "stuff.bypass.sudo"