# Plugin by Jon1Games
# Discord: jon1games
# GitHub: https://github.com/Jon1Games/

# Implementet plugins (usable in this Plugin):
# Minimessage (https://docs.advntr.dev/minimessage/format.html)

EnableCalculatorCommand: true

CustomJoinQuitMessage:
  Enabled: true
  Messages:
  # Player placeholder: <player>
    JoinMessage: "<gray>[</gray><green>+</green><gray>]</gray> <player>"
    LeaveMessage: "<gray>[</gray><red>-</red><gray>]</gray> <player>"

MsgCommand:
  Enabled: true
  ArgumentName: "Nachricht"
  MessageFormat:
  # for MSGFormat use: <fromplayer> and <toplayer>
  # Use <message> as the Message given by the Player
    # Message for the MSG target
    To: "<gray>[</gray>Prefix<gray>]</gray> <fromplayer> -> <toplayer> <gold>:</gold> <message>"
    # Message for the MSG sender
    From: "<gray>[</gray>Prefix<gray>]</gray> <fromplayer> -> <toplayer> <gold>:</gold> <message>"

FlyCommand:
  Enabled: true
  Permission: "stuff.fly"
  Messages:
    Self:
      EnterFlyMode: "Du bist in den Flugmodus gegangen."
      ExitFlyMode: "Du bist aus dem Flugmodus gegangen."
      ReturnInEnterFlyMode: "Der Flugmodus ist Aktiviert."
    Other:
    # Player placeholder: <player>
      Self:
        EnterFlyMode: "Du hast <green><player></green> in den Flugmodus gesetzt."
        ExitFlyMode: "Du hast <green><player></green> aus dem Flugmodus geholt."
      Other:
        EnterFlyMode: "Du wurdest von <green><player></green> in den Flugmodus gesetzt."
        OtherOtherExitFlyMode: "Du wurdest von <green><player></green> aus dem Flugmodus geholt."



SpeedCommand:
  Enabled: true
  Permission: "stuff.fly"
  Messages:
  # Speed placeholder: <speed>
    Self:
      NewSpeed: "Deine neue Geschwindigkeit ist nun <gold><speed></gold>."
      ReturnSpeed: "Deine Geschwindigkeit ist <gold><speed></gold>"
    Other:
    # Player placeholder: <player>
      SelfNewSpeed: "Deine neue Geschwindigkeit wurde von <green><player></green> auf <gold><speed></gold> gesetzt."
      OtherNewSpeed: "Du hast die Geschwindigkeit von <green><player></green> auf <gold><speed></gold>."

GamemodeCommand:
  Enabled: true
  messages:
  # Player placeholder: <player> (only for the Other section)
    Creative:
      Permission: "stuff.gamemode.creative"
      Self: "Dein Spielmodus wurde auf Kreativ gesetzt."
      Other:
        Self: "Du hast <green><player></green> in den Kreativ Modus gesetzt."
        Other: "Du wurdest von <green><player></green> in den Kreativ Modus gesetzt."
    Spectator:
      Permission: "stuff.gamemode.spectator"
      Self : "Dein Spielmodus wurde auf Zuschauer gesetzt."
      Other:
        Self : "Du hast <green><player></green> in den Zuschauer Modus gesetzt."
        Other : "Du wurdest von <green><player></green> in den Zuschauer Modus gesetzt."
    Adventure:
      Permission: "stuff.gamemode.adventure"
      Self : "Dein Spielmodus wurde auf Abenteuer gesetzt."
      Other:
        Self : "Du hast <green><player></green> in den Abenteuer Modus gesetzt."
        Other : "Du wurdest von <green><player></green> in den Abenteuer Modus gesetzt."
    Survival:
      Permission: "stuff.gamemode.survival"
      Self : "Dein Spielmodus wurde auf Überleben gesetzt."
      Other:
        Self : "Du hast <green><player></green> in den Überleben Modus gesetzt."
        Other : "Du wurdest von <green><player></green> in den Überleben Modus gesetzt."

PortableInventoryCommand:
  Enabled: true
  WorkbenchPermission: "stuff.portableinventory.workbench"
  AnvilPermission: "stuff.portableinventory.anvil"
  GrindstonePermission: "stuff.portableinventory.grindstone"
  SmithingtablePermission: "stuff.portableinventory.smithingtable"

Format:
  Chat:
    Enabled: true
    # Placeholder: <player>, <message>
    Format: "<player> <gray><message></gray>"

TpaCommand:
  Enabled: true
  Delay:
    Enabled: true
    Amount: 3
  Messages:
  # PLaceholder: <player> <delay>
    Tpa:
      Sender: "Du hast <player> eine Teleportanfrage geschickt."
      Reciver: "Du hast eine Teleportanfrage von <player> bekommen.<br><red>Ablehnen</red> <green>Annehmen</green>"
      Self: "Du kannst dir nicht selbst eine Teleportanfrage senden."
    Tpaccept:
      Sender: "Der Spieler <player> hat deine Teleportanfrage angenommen."
      Reciver: "Du hast die Teleportanfrage von <player> angenommen."
      NoRequest: "Du hast keine Teleportanfrage von <player> bekommen."
      Timeout: "Diese Teleportanfrage ist abgelaufen."
    Delay: "Bewege dich nicht, Du wirst in <delay> Sekunden Teleportiert..."
    Error:
      Move: "Der Teleport wurde abgebrochen, da du dich bewegt hast."