# Plugin by Jon1Games
# Discord: jon1games
# GitHub: https://github.com/Jon1Games/

# Implemented plugins (usable in this Plugin):
# Minimessage (https://docs.advntr.dev/minimessage/format.html)

# Required Plugins
# LuckPerms
# PlaceHolderApi

EnableCalculatorCommand: true

CustomJoinQuitMessage:
  Enabled: true
  Messages:
  # Player placeholder: <player>
    JoinMessage: "<gray>[</gray><green>+</green><gray>]</gray> <player>"
    LeaveMessage: "<gray>[</gray><red>-</red><gray>]</gray> <player>"

MsgCommand:
  Enabled: true
  ArgumentName: "Nachricht"
  MessageFormat:
  # for MSGFormat use: <fromplayer> and <toplayer>
  # Use <message> as the Message given by the Player
    # Message for the MSG target
    To: "<gray>[</gray>Prefix<gray>]</gray> <fromplayer> -> <toplayer> <gold>:</gold> <message>"
    # Message for the MSG sender
    From: "<gray>[</gray>Prefix<gray>]</gray> <fromplayer> -> <toplayer> <gold>:</gold> <message>"

FlyCommand:
  Enabled: true
  Permission: "stuff.fly"
  Messages:
    Self:
      EnterFlyMode: "Du befindest in den Flugmodus gegangen."
      ExitFlyMode: "Du befindest aus dem Flugmodus gegangen."
      ReturnInEnterFlyMode: "Der Flugmodus ist Aktiviert."
    Other:
    # Player placeholder: <player>
      Self:
        EnterFlyMode: "Du hast <green><player></green> in den Flugmodus gesetzt."
        ExitFlyMode: "Du hast <green><player></green> aus dem Flugmodus geholt."
      Other:
        EnterFlyMode: "Du wurdest von <green><player></green> in den Flugmodus gesetzt."
        OtherOtherExitFlyMode: "Du wurdest von <green><player></green> aus dem Flugmodus geholt."



SpeedCommand:
  Enabled: true
  Permission: "stuff.speed"
  Messages:
  # Speed placeholder: <speed>
    Self:
      NewSpeed: "Deine neue Geschwindigkeit ist nun <gold><speed></gold>."
      ReturnSpeed: "Deine Geschwindigkeit ist <gold><speed></gold>"
    Other:
    # Player placeholder: <player>
      SelfNewSpeed: "Deine neue Geschwindigkeit wurde von <green><player></green> auf <gold><speed></gold> gesetzt."
      OtherNewSpeed: "Du hast die Geschwindigkeit von <green><player></green> auf <gold><speed></gold>."

GamemodeCommand:
  Enabled: true
  messages:
  # Player placeholder: <player> (only for the Other section)
    Creative:
      Permission: "stuff.gamemode.creative"
      Self: "Dein Spielmodus wurde auf Kreativ gesetzt."
      Other:
        Self: "Du hast <green><player></green> in den Kreativ Modus gesetzt."
        Other: "Du wurdest von <green><player></green> in den Kreativ Modus gesetzt."
    Spectator:
      Permission: "stuff.gamemode.spectator"
      Self : "Dein Spielmodus wurde auf Zuschauer gesetzt."
      Other:
        Self : "Du hast <green><player></green> in den Zuschauer Modus gesetzt."
        Other : "Du wurdest von <green><player></green> in den Zuschauer Modus gesetzt."
    Adventure:
      Permission: "stuff.gamemode.adventure"
      Self : "Dein Spielmodus wurde auf Abenteuer gesetzt."
      Other:
        Self : "Du hast <green><player></green> in den Abenteuer Modus gesetzt."
        Other : "Du wurdest von <green><player></green> in den Abenteuer Modus gesetzt."
    Survival:
      Permission: "stuff.gamemode.survival"
      Self : "Dein Spielmodus wurde auf Überleben gesetzt."
      Other:
        Self : "Du hast <green><player></green> in den Überleben Modus gesetzt."
        Other : "Du wurdest von <green><player></green> in den Überleben Modus gesetzt."

PortableInventoryCommand:
  Enabled: true
  WorkbenchPermission: "stuff.portableinventory.workbench"
  AnvilPermission: "stuff.portableinventory.anvil"
  GrindstonePermission: "stuff.portableinventory.grindstone"
  SmithingtablePermission: "stuff.portableinventory.smithingtable"

Format:
  PlayerNames:
    Enabled: true
    Prefix:
      Enabled: true
      Prefix: "%luckperms_prefix% "
    Suffix:
      Enabled: true
      Suffix: " %luckperms_suffix%"
    TabSorting:
        Enabled: true
        MaxWeight: 1000
  Chat:
    Enabled: true
    # Placeholder: <player>, <message>
    Format: "<player> <gray><message></gray>"
    # options vanilla (&4 text in dark red) and minimessage ( <red> text in red )
    ColorType: minimessage
    InChatPlaceholder:
      # displaying held item, placeholder: <i> or <I> (only supported by ColorType: minimessage)
      ItemInHand: true

InfoCommands:
  Enabled: false
  Links:
    Enabled: false
    Messages: "Ein Link Text"
  Discord:
    Enabled: false
    Message: "Unseren Discord Server findet ihr unterdem folgendem link<br> <click:open_url:'https://discord.gaminglounge.me'>https://discord.gaminglounge.me</click>"
  TikTok:
    Enabled: false
    Message: "Unseren TikTok Account findet ihr unterdem folgendem link<br> <click:open_url:'https://tiktok.gaminglounge.me'>https://tiktok.gaminglounge.me</click>"
  Instagram:
    Enabled: false
    Message: "Unser Instagram Profiel findet ihr unterdem folgendem link<br> <click:open_url:'https://instagram.gaminglounge.me'>https://instagram.gaminglounge.me</click>"
  Twitter:
    Enabled: false
    Message: "Unser Twitter Profiel findet ihr unterdem folgendem link<br> <click:open_url:'https://twitter.exmaple.me'>https://twitter.exmaple.me</click>"
  X:
    Enabled: false
    Message: "Unser X Profiel findet ihr unterdem folgendem link<br> <click:open_url:'https://X.exmaple.me'>https://X.exmaple.me</click>"
  MinecraftMap:
    Enabled: false
    Message: "Unser ingame Minecraft Wellt findet ihr unterdem folgendem link<br> <click:open_url:'https://map.gaminglounge.me/minecraft/freebuild/'>https://map.gaminglounge.me/minecraft/freebuild/</click>"

PlayTimeCommand:
  Enabled: true
  # Placeholders: for both: <days> <hours> <min> <sec> , for other: <player>
  Messages:
    self: "<green>Du hast <days> Tage, <hours> Stunden, <min> Minuten und <sec> Sekunden Spielzeit"
    other: "<green><player> hat <days> Tage, <hours> Stunden, <min> Minuten und <sec> Sekunden Spielzeit"

PingCommand:
  Enabled: true
  # Placeholders: for both: <ping> , for other: <player>
  Messages:
    self: "Dein Ping beträgt <gold><ping><reset>."
    other: "Der Ping von <green><player><reset> Ping beträgt <gold><ping><reset>."