name: Stuff
version: "${version}"
main: de.jonas.stuff.Stuff
api-version: "1.21.1"
loader: de.jonas.stuff.Stuffloader
permissions:
  stuff.teleport.tpa.cooldown.bypass:
  stuff.teleport.tpa.notmovefor.bypass:
  stuff.teleport.rtp.cooldown.bypass:
  stuff.teleport.rtp.notmovefor.bypass:
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
