name: Stuff
version: "${version}"
main: de.jonas.stuff.Stuff
api-version: "1.21.8"
loader: de.jonas.stuff.Stuffloader
Authors:
  - "Jon1Games"
permissions:
  stuff.teleport.tpa.cooldown.bypass:
  stuff.teleport.tpa.notmovefor.bypass:
  stuff.teleport.rtp.cooldown.bypass:
  stuff.teleport.rtp.notmovefor.bypass:
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    ConfigAPI:
      load: BEFORE
      required: true
      join-classpath: true
