name: Stuff
version: "${version}"
main: de.jonas.stuff.Stuff
api-version: "1.21"
loader: de.jonas.stuff.Stuffloader
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
